import { useChatStore } from '../store/chat.store';

export const useChats = () => {
  const {
    conversations,
    allUsers,
    selectedConversation,
    messages,
    onlineUsers,
    typingUsers,
    loading,
    error,
    fetchConversations,
    fetchConversationById,
    fetchUsers,
    fetchMessages,
    sendMessage,
    addMessage,
    updateMessage,
    deleteMessage,
    setMessages,
    setConversations,
    setAllUsers,
    selectConversation,
    createRoom,
    clearMessages,
    setOnlineUsers,
    setTypingUsers,
    setLoading,
    setError,
  } = useChatStore();

  return {
    conversations,
    allUsers,
    selectedConversation,
    messages,
    onlineUsers,
    typingUsers,
    loading,
    error,
    fetchConversations,
    fetchConversationById,
    fetchUsers,
    fetchMessages,
    sendMessage,
    addMessage,
    updateMessage,
    deleteMessage,
    setMessages,
    setConversations,
    setAllUsers,
    selectConversation,
    createRoom,
    clearMessages,
    setOnlineUsers,
    setTypingUsers,
    setLoading,
    setError,
  };
};
